#' Compute Psi for Proxy VAR
#'
#' Calculates the Psi matrix for proxy VAR analysis.
#'
#' @param x A VAR model object (class "varest").
#' @param nstep The number of forecast steps.
#' @param instrumented A character string for the instrumented variable.
#' @return A 3D array representing the Psi matrix.
#' @export
Psi.varest <- function (x, nstep = 10, instrumented){
  if (!is(x, "varest")) {
    stop("\nPlease provide an object of class 'varest', generated by 'VAR()'.\n")
  }
  nstep <- abs(as.integer(nstep))
  Phi <- Phi(x, nstep = nstep)
  Psi <- array(0, dim = dim(Phi))
  params <- ncol(x$datamat[, -c(1:x$K)])
  sigma.u <- crossprod(residuals(x))/(x$obs - params)
  P <- sigma.u
  P[] <- 0
  P[, instrumented]
  P[, instrumented] <- rep(as.numeric(coefs), length.out = nrow(P))
  dim3 <- dim(Phi)[3]
  for (i in 1:dim3) {
    Psi[, , i] <- Phi[, , i] %*% P
  }
  return(Psi)
}
